### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by JVilo** [aarnif/tsoha-forum#1]
Sovelluksen teko näyttää olevan hyvällä mallilla.
koin sovelluksessa liikkumisen hieman hankalaksi kun olin päätynyt lopulta sisään keskustelun sisältö sivulle sieltä pois pääseminen vaatii sovelluksen nimen painamista joka ei sinällään tuntunut aivan intuitiivisellta. Keskusteluissa liikkuminen ja toiminnan ymmärtäminen vaati hieman klikkailua.  Jonkillainen ohjeistus esim "paina keskustelun otsikkoa jotta pääset...".
Voi toki olla että ulkonäön muokkaus parantaa käytettävyyttä.

Koodi näyttää olevan hyvin kirjoitettu. Huomaa että ei ole ensimmäinen kerta kun kirjoitat koodia.
En ymmärrä miksi routes.py;ssä käytät melkkeen jokaisessa @app.route methods=["GET", "POST"]), vaikka koodissa ei välttämättä edes mainita posti osuutta ollenkaan?
Itse melko tuoreena koodaajana opin koodistasi miten itse olisin voinut tehdä asioita omassa sovelluksessani.

Muutoin sovellus vaikuttaa viimeistelyävailla valmiilta.

**Comment by aarnif** [comment]
Kiitos kommenteista!

Päivitin koodia palautteesi perusteella.

Routeissa tulee aina mainita kaikki sallitut http-pyyntömetodit. 
Koska kyseisiin routteihin pystyy tekemään myös POST-pyyntöjä, on ne lisätty methods-parametriin.

Lisäsin kuitenkin koodin selkeyttämiseksi if-haarat myös POST-pyyntöjen käsittelyyn.
