### ISSUE TITLE
Vertaisarviointi II

### ISSUE THREAD

**Issue by mollila666** [aarnif/tsoha-forum#2]
Käytettävyys ja ulkoasu erinomaisia lähes täydellinen, ainoat kommenttit:

Kun luon uutta aluetta, palkit 'Peruuta' ja 'Luo alue' ovat 'Created By aarnif' päällä, sitä ei näy (pieni yksityiskohta, joka ei haittaa käyttöä).
Sama toistuu myös toisissa paikoissa, esim jos muokkaan viestiä, palkit menevät päällekkäin.

'Navigaatiopalkilla' pääsee tyypillisesti yhden askeleen taaksepäin, joskus olisi hyvä päästä ehkä suoraan alkupisteeseen myös, 
takaisin nappula löytyy myös selaimesta.

Testiympäristössä toimii fantastisesti, ei ollut ollenkaan hidas, täydellinen!

Koodi on kirjoitettu 'by the book', huomioiden kaikki mahdolliset tyyliohjeet.

Tietoturva:

Loin uuden käyttäjän user666 (ei admin oikeuksia), jolle kerrotaan pääsivulla:

	Salaiset Alueet

	Sinulla ei ole pääsyä salaisiin alueisiin tai niitä ei ole olemassa. 

Mutta jos user666 heittää selaimeen copy-pastella:

https://tsoha-forum.onrender.com/subforums/6/threads/11

hän näkee:

    Olet kirjautunut nimellä: user666

    Kirjaudu ulos

	Ylläpidon Sisäiset Keskustelut

	admin

		09-09-2024 09:00

	Muistakaa tarkistaa uusien käyttäjien hyväksyntälistat viikoittain. etc...

Voin myös muokata salaisia viestejä:

	Muistakaa tarkistaa uusien käyttäjien hyväksyntälistat viikoittain. Ei muisteta, olen uuser666, eikä minulla ole admin oikeuksia.

Kun olen muokannut yllä esitettyä viestiä => sovellun näyttää yhä että viestin on kirjoittanut 'Admin', muokkaajan nimeä ei mainita, tämä pitäisi korjata.

User666 voi myös lisätä viestejä salatulle alueelle, riittää kun sinne siirtyy copy-pastella eikä sovelluksen linkeistä (kun sellaisia ei ole).

	Myös viestin kirjoittaminen onnistuu salattuun keskusteluun. T: user666

Viestien tuhoaminen salatulta alueelta onnistuu myös.

Tietoturva asioita kannattaa ehkä hieman muokata. Muuten valmis mielestäni!

**Comment by aarnif** [comment]
Kiitos hyvistä kehitysideoista!

Nämä kaikki pitäisi nyt olla korjattu.
